### ISSUE TITLE
Acciones del carrito

### ISSUE THREAD

**Issue by Piarrot** [1022FSNSANCN02ARED/grupo-03#1]
Hola Grupo! 
Les queria hacer una consulta. En el carrito: https://github.com/1022FSNSANCN02ARED/grupo-03/blob/dd1462c52b9628f604f43e0706cc3e6d9a3d38ed/wireframes/desktop/carrito-desktop.png

¿No les parece que se deberian poder borrar elementos de la operación? ¿O cómo piensan manejar eso?

**Comment by IPardo1** [comment]
Hola Pablo, tomamos la decisión de agregar un botón con una cruz para quitar el elemento del carrito y otro botón para editarlo.
