### ISSUE TITLE
Responsive Header

### ISSUE THREAD

**Issue by LuiosDyet** [1022FSNSANCN02ARED/grupo-03#2]
Cuidado con el header, cuando lo pasan a mobile no se ve ni register ni el perfil pero si el login y el carrito. No me parece que sea el comportamiento que estaban buscando. Es probable que tengan que corregir esto.

**Comment by Piarrot** [comment]
Agregaron un boton de menu-hamburguesa, aunque no está del todo implementado.
Estoy suponiendo que ya lo tienen en cuenta entonces, pero por las dudas lo dejo abierto para que no se olviden de terminar de implementarlo.

**Comment by fede-vazquez** [comment]
Buenas Luis y Pablo, disculpen que no hayamos respondido al issue. Se nos pasó por alto.
La idea original era que el botón de "ingresar" sea visible en todos los tamaños de pantalla. Pero después de lo que había mandado Luis estuvimos viendo otras páginas y solo tenían el menú hamburguesa y el carrito.
Recién subí al repo la corrección.
Ahora el botón no se muestra en mobile, se muestra a partir del media query de 761px o más.
