### ISSUE TITLE
Redirección header

### ISSUE THREAD

**Issue by LuiosDyet** [1022FSNSANCN02ARED/grupo-03#3]
Es usual hoy en día que al hacer click en el header te lleva al inicio. Capaz sería un buen feature para agregar.

**Comment by fede-vazquez** [comment]
Buenas Luis.
¿Con header te referís al logo que esta en el nav?
Yo lo entendí así, y lo implemente en el proyecto con una etiqueta "a" envolviendo a la img del Logo. Que era algo que estaba pensado, pero olvide de colocarlo.
Gracias por avisar.
Y si sabes de alguna forma que sea mas semánticamente correcta, me gustaría saberlo. Gracias

**Comment by LuiosDyet** [comment]
Si, me referia a eso nomás. Perfecto
